### ISSUE TITLE
Switch to PEP 8

### ISSUE THREAD

**Issue by Florob** [voc/voctomix#102]
I don't generally care much about a projects coding style, however I think there is something to be said for consistency. The Python community has converged on following PEP 8, to the point where tooling routinely warns about not following it.

I think switching to PEP 8 would slightly reduce the entry barrier for new contributors. It also improves the experience of using some of the available Python tooling. E.g. using syntastic the pep8 warnings that occur for almost every line currently hide other more useful warnings.

**Comment by MaZderMind** [comment]
Yes, I agree on that. Let's open a branch and start redoing that. We could also add automated checks for that, but'll have to see how picky that is.

Would you mind adding a branch and your check-command into a script in the root-dir as a starter?

**Comment by Florob** [comment]
Not at all, though that script amounts to `pep8 .`.
One way to move forward would be using `autopep8` on each file and reviewing the results.

**Comment by Florob** [comment]
The pep8 branch now contains code that at least makes the `pep8` tool happy.
It's the result of a combination of `autopep8`, `pep8ify`, and manual editing.
I've tested and reviewed the diff rather thoroughly, but I'd still like a second pair of eyes before merging.
`git diff -b`/`git log -p -b` are rather helpful for ignoring pure indentation changes.
