### ISSUE TITLE
One-time handlers break other connection signal handlers

### ISSUE THREAD

**Issue by Florob** [voc/voctomix#103]
As currently written, when a one-time handler fires it removes all signal handlers registered for the signal, instead of just itself.

**Comment by MaZderMind** [comment]
can you clarify on that? I'm not sure what one-time-hander you exactly talk about

**Comment by Florob** [comment]
One-time handlers added using [`Connection.one()`](https://github.com/voc/voctomix/blob/aa2e12b92df3400e6f9cb89afc16eb968b0c2491/voctogui/lib/connection.py#L147).
AFAICT they are currently unused, I just randomly stumbled over the code.

**Comment by MaZderMind** [comment]
I'd probably just remove them. Unused code is not good.
