### ISSUE TITLE
Adjustable Volume of Pauseloop

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#104]
The Volume-Multiplier (= the Value of the level-Property of the audiomixer-Element) should be configurable. It's currently hardcoded to a value of 1.0

**Comment by MaZderMind** [comment]
alternatively add an auto-adjusting filter to the source-ffmpeg: https://ffmpeg.org/ffmpeg-filters.html#loudnorm

**Comment by DavidVentura** [comment]
Consider #130 or something similar?
