### ISSUE TITLE
Mehr Aux-Wege / Configurable AUX ports

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#113]
Wir sollten uns ein Konzept überlegen, wie wir mehr Aux-Wege konfigurierbar machen können, welche z.B. wahlfreie Video- und Audio-Quellen mischen und ggf. auch Audiokanäle Stacken kann (z.B. Slide-Stream mit allen Audiokanälen)

(translation)
We should think of a Concept to have configurable AUX outputs. This should allow any video or audio source to be mixed (or not) and send to an output port. One example would be a slide stream with all audio channels.

**Comment by derpeter** [comment]
We may need to separate between near real time aux and recording aux. 

An example for the first kind is to show the picture of a camera on the beamer on stage.
An example for the second kind is to record the slides separate of the mixed video.

For the first type we may want to take some shortcuts in vocotore to get the delay low. Maybe even involving external hardware like the opsis could be an option here.

**Comment by MaZderMind** [comment]
implemented this outside of voctomix
