### ISSUE TITLE
add speaker desk postion to config

### ISSUE THREAD

**Issue by derpeter** [voc/voctomix#114]
In the composite views it look strange if the speaker is on the right side of the slides if he is in reality on the left side. An optional config option could change the composed view to reflect that.

**Comment by fightling** [comment]
Like I understand it would be helpful to have a configuration file option like this:
```
[compositeview]
forceA=cam1
;forceB=cam1
```
This could cause voctogui to

* force `cam1` to be `A` (or `B`) when switching to any side-by-side mode and 
* disable or hide the A/B buttons within the preview bar. 

Is this what you want?

**Comment by MaZderMind** [comment]
@fightling Take a look at this image: 
![65-hd_preview](https://user-images.githubusercontent.com/142237/40889502-0c47baa6-6768-11e8-9151-7c45a3668a83.jpg)

The Speaker's Desk was, in reality, left of the projection surface, so he points to his right side.
In the composition the Slides are on the other side, so it looks like he's pointing nowhere.

How I understood @derpeter's Request was to have a simple Switch in the config which would flip the Compositions on the horizontal Axis, allowing to quickly adjust for different room setups.

One drawback would be, that the Background-Artwork would probably be prepared for such a flip and we might even need to prepare two sets of artwork.

**Comment by fightling** [comment]
This can be done with the new transitions
