### ISSUE TITLE
Add composited source to support Lower Thirds

### ISSUE THREAD

**Issue by danimo** [voc/voctomix#115]
It would be nice to provide some way to integrate Lower Thirds ("Bauchbinden"):

![image](https://cloud.githubusercontent.com/assets/1315934/20687638/90ed6c82-b5bd-11e6-8c16-c9b77957a4fa.png)

(CC-BY-SA from https://en.wikipedia.org/wiki/Lower_third#/media/File:Bauchbinde_TV_description.jpg)

AFAIK, in professional environment those get created by a separate piece of hardware, and are fed into video mixers which then superimpose them to the live feed via chroma keying or make use of the alpha channel for compositing.

Similar to other environments, Voctomix itself should not have any dealing with how to create the lower third graphics. What it should be capable of is providing a source that can be superimposed on top of the current mix, rather than toggled. I am not sure what a good UI for this would look like, but even without preview, a button to fade in/out a particular channel would be nice. Generating the graphics would be another tool's job.

**Comment by fightling** [comment]
Now implemented on branch voctomix-overlay.

**Comment by fightling** [comment]
solved in voctomix2
