### ISSUE TITLE
If config file isn't found, voctocore silently ignores it without any warning or anything

### ISSUE THREAD

**Issue by mithro** [voc/voctomix#116]
Run `./voctocore/voctocore.py -v -i config.inii` and wonder why voctomix isn't using your configuration. Some type of error message would be nice.

**Comment by MaZderMind** [comment]
config.p actually does report which files it tried to parse and which succeeded: https://github.com/voc/voctomix/blob/master/voctocore/lib/config.py#L33

But this is only visible when ran with -vv and also does not abort the startup.
Specifying a File with --ini does indeed clearly indicate that the user wants this file to be parsed and failing to do so should result in an error & abort rather then a warning.
