### ISSUE TITLE
Voctocore leaks file descriptors

### ISSUE THREAD

**Issue by krokodilerian** [voc/voctomix#117]
voctocore/lib/tcpmulticonnection.py is missing conn.close() before it gets deleted (inclose_connection(), line 46) . This leads to leaking a file descriptor every time a connection is opened and closed. There might be the same issue in voctocore/lib/tcpsingleconnection.py, with one self.currentConnection.close().

This was detected with a script that generated screenshots of the output and the inputs on every second.

**Comment by MaZderMind** [comment]
If you already have a Test-Setup and also already found the place to fiy it, would you mind sending a Pull Request?

**Comment by krokodilerian** [comment]
@MaZderMind , I've opened https://github.com/voc/voctomix/pull/118, and this works-for-me(tm), but someone with more experience in python should check it.

**Comment by MaZderMind** [comment]
looks good to me, merged.
