### ISSUE TITLE
Store name of video Angel somewhere

### ISSUE THREAD

**Issue by derpeter** [voc/voctomix#122]
It would be very nice to know who has operated the video mixer for a specific talk. e.g. the Angel for the lora wan talk would need much more training. We could write an simple text file and give the operator an input filed for its nickname

**Comment by davidak** [comment]
The Engelsystem has the data, so why not get an export before it shuts down?
There would also be an e-mail address to contact that person.
This might need to be opt-in.

**Comment by derpeter** [comment]
if that is possible ( from a privacy point of view ) that would be an option. Letting the operator type is name is more an opt-in thing.

**Comment by davidak** [comment]
The opt-in bit could also bet set while unlocking the camera and mixer angels.

"Can we contact you with feedback to your work? You can change this option later yourself in the Engelsystem."

So everyone has to actively decide it. But that situation is already very stressfull for everyone.

**Comment by derpeter** [comment]
it would be more like "are we allows to store you name, nickname and mail together with the talk you worked on to improve the quality". So if someone would implement that in the enegelsystem and find a way to export that information for us together with the talk id that would be awesome

**Comment by MaZderMind** [comment]
I don't see how we can include this in voctomix without mixing up multiple, not related systems. Voctomix is a video-mixing-software, it does not care about the angel-system and I don't want to mix them up.

It should be trivial to get the information, which talk was mixed by which mixer-angel from the angel-system, so we should better discuss there, how we can export and manage this information in compliance with their privacy rules.

**Comment by derpeter** [comment]
just by writing a machine readable file with time, name and room. We can easily import that e.g. into the tracker. I dont see where this mixes system on the other hand involving the engelsystem mixes system even more

Also it was already mentioned that we can get from the angel system and also the privacy issue there. On top of this it would only work for conference with angel system.

**Comment by saerdnaer** [comment]
The Engelsystem has an API – a simple cron job or worker task fetching this information and storing it as part of the recording ticket in the C3Tracker would be the most suitable option.
