### ISSUE TITLE
Packages for Debian

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#13]
We should provide all files necessary to build debs from this including systemd/init-startup-files, especially to help people getting all dependencies together (see #4)

**Comment by a-tze** [comment]
I propose building 3 packages:
- voctomix-common - a base package to satisfy the common dependencies on other packages
- voctomix-core
- voctomix-gui

Should the examples be included in -core or in a separate -doc package? Since package size will be fairly small and the packages won't run on embedded devices anyway, a -doc package seems unnecessary.

**Comment by MaZderMind** [comment]
I agree that maybe an extra -doc package is of little use. The Scripts belong more to the core (where they originally were located and where we/you could move then back, if we package it the way you describe) but still they are more like documentation and should be placed in a location that makes this clear.

**Comment by a-tze** [comment]
I would place the scripts in `/usr/share/doc/voctomix[-core]/examples/` . 

Moving them back in the repository should not be necessary, because I tend to create one single `debian` subfolder for the whole source. The placement of the files when the package is installed is configured separately.

**Comment by baldurmen** [comment]
Hi! We were thinking of using voctomix at DebConf 16 in Cape Town and having debian packages would really be awesome!

Do you think having it packaged by then (~23 June) is feasible?

**Comment by MaZderMind** [comment]
@baldurmen Hi! Awsome that you're thinking about using voctomix. I don't think we will have time to create Packages until that date, but if you'd be willing to work on this I'll happily support you and accept PRs.

**Comment by derpeter** [comment]
@MaZderMind you may want to mention that there are gstreamer packages for jessie (as far as i know) so deploying vocto is only a git pull when these packages are installed.

**Comment by MaZderMind** [comment]
@derpeter we have somewhat unmaintained packages for gstreamer 1.6 built against deb-multimedia here: https://c3voc.de/voctomix/.

We also have gstreamer 1.6 packages built against our voc-libraries, but they may be not-redistributable because of linking in libfdk_aac.

For general most users coming into trying voctomix, using ubuntu 15.10 wily is the way to go, because it already ships with an 1.6 gstreamer, but having a more official way for debian would surely be appreciated.

**Comment by derpeter** [comment]
its called debconf ;-) ubuntu might not be the most desired option ;-) 
and using the librarys it has been tested with is (except of the libfdk_aac problem) 
a good idea when you dont have time to debug ;-)

**Comment by h01ger** [comment]
I'm on it, see
https://github.com/h01ger/voctomix/tree/debian
and
https://bugs.debian.org/822805

**Comment by h01ger** [comment]
the open question is about the default-config.ini, where do these files have to be placed? just in the current directory?

**Comment by h01ger** [comment]
packaging now also available at https://anonscm.debian.org/git/collab-maint/voctomix.git which is also the future url for the packaging git repo.
the packaging is ready for upload (and further tests), just waiting for fixing another small issue (as discussed right now on the #voctomix irc channel… :)

**Comment by h01ger** [comment]
https://tracker.debian.org/pkg/voctomix

this has been done :)
