### ISSUE TITLE
Documentation: side by side config as images

### ISSUE THREAD

**Issue by saerdnaer** [voc/voctomix#131]
When graphic designers are creating artwork (e.g. bg loop) for usage in voctomix, they need the placement of source A and B in [side-by-side-equal] and [side-by-side-preview] view as defined in https://github.com/voc/voctomix/blob/master/voctocore/default-config.ini#L34-L53 .

It would be nice if we can send them images/template files where this messurements are shown – e.g. 

<img width="1679" alt="pastedgraphic-3" src="https://cloud.githubusercontent.com/assets/40266/24840604/3ab09c48-1d70-11e7-98e6-569970d152d2.png">

**Comment by Florob** [comment]
Fundamentally I'm not entirely sure this is the right way to things. In terms of getting good designs we might want to let the designer run free and adjust the configuration accordingly. As long as they leave enough room for the videos that shouldn't be overly problematic.
That said, I've played with writing a small template generator. It generates SVGs with different composite modes as different Inkscape layers. You can save these as XCF in Inkscape and go to e.g. PSD from there. Allegedly Illustrator will also treat the SVG as having sub-layers for each composite mode.
Config is currently hard coded, but could be read from the voctocore config, if people think this is a useful tool to have.
* [Script](http://babelmonkeys.de/~florob/voctomix/mk_template.py)
* [SVG](http://babelmonkeys.de/~florob/voctomix/template.svg)
* [PSD](http://babelmonkeys.de/~florob/voctomix/template.psd)

**Comment by dedeibel** [comment]
Export the views as png and get an animated preview using:

`ffmpeg -i bgloop.ts -i preview.png -filter_complex "scale=1920:1080,overlay=main_w-overlay_w-0:0" -b:v 6000k -f nut - | ffplay -i -`

**Comment by duzy** [comment]
This project reminds me the original [gst-switch](https://github.com/duzy/gst-switch), lol.

**Comment by MaZderMind** [comment]
@duzy yes, it is based upon gst-switch and inherited a lot of its original design ideas.

**Comment by duzy** [comment]
@MaZderMind yes, Peter, I can see that. The design model is almost the same the original, as looking at your UI, it reminds me the pipelines. Thanks for utilizing the design and make it better in your own fashion.

**Comment by MaZderMind** [comment]
fwiw: i added the py and the svg to the git-repo: https://github.com/voc/voctomix/tree/master/doc/composition-mode-images

i didn't add the psd.
