### ISSUE TITLE
can voctomix add multi video stream(three or more)?

### ISSUE THREAD

**Issue by notedit** [voc/voctomix#132]

**Comment by a-tze** [comment]
Please explain. What do you exactly mean with "add"?

**Comment by notedit** [comment]
if  i have three camera,  one big camera video and two small camera video.

the two samll  came video is above on big camera video.

**Comment by notedit** [comment]
it seems that voctomic can only mix  two video  one time.

**Comment by a-tze** [comment]
So you mean Picture-in-Picture with 3 sources?

**Comment by notedit** [comment]
yes

**Comment by MaZderMind** [comment]
@notedit Currently Voctomix does exact 4 Composition modes, whereof 1 shows only 1 Video (=Fullscreen) and the other 3 show a combination of 2 Videos.

Voctomix has no composition mode with 3 or more videos, but that's not a technical limitation but has rather been a design decision made in the past.
