### ISSUE TITLE
How to add 2 webcams /dev/video0 /dev/video1 as camera A and B of mixer

### ISSUE THREAD

**Issue by allegfede** [voc/voctomix#134]
maybe i'm a bit dumb, but really dvswitch is clear on how to add signals to the switcher ....

With VOCTO i managed to start the core and the gui, but have not found Where to store che config file AND how to add signals to the switch ....

Could you please make an howto?

**Comment by allegfede** [comment]
i see on the main page there are exampls that have to help me do what i need, bur are quite cryptic for who is not python addicted :D

**Comment by MaZderMind** [comment]
Hi. Please accept that this is not a Support-Forum, it's an Development-Issue-Tracker.
For Support please join #voctomix on hackint.eu (IRC).

Regarding you Question: I have not used V4L2 as input-sources yet, we're using Blackmagic-Capture-Cards. I don't know how or if it might work, but I think that there might be some people on IRC which have used V4L2. On the other hand the examples are quite extensive and it should not be hard to modify one of the ffmpeg-examples to suite your needs.

Voctomix ist not an out-of-the-box solution, it is a set of tools which requires quite a lot of glue-work around it to make it a useful solution. Looking at our config-management might give some insight: https://github.com/voc/cm/blob/b271a19/ansible/roles/encoder/tasks/encodermode-voctomix.yml
