### ISSUE TITLE
Add VSource for looping clips

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#144]
With the new internal sources for decklink & images, it would be cool to also have an internal source for looping background & pause-clip.

Possibly the loop-source could decompress the clip on bootup and store it uncompressed, thus reducing the runtime-cpu usage.

**Comment by MaZderMind** [comment]
https://github.com/voc/voctomix/blob/master/voctocore/lib/sources/imgvsource.py

https://github.com/voc/voctomix/blob/master/example-scripts/gstreamer/source-background-loop.py

**Comment by fightling** [comment]
Danimo did that in voctomix2. I think he's still working at it.
