### ISSUE TITLE
Configurable number of Audio-Streams for Translations

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#145]
Prior Information
-----------------
The interaudio-Elements used to connect the functional blocks inside voctomix are fixed to carry one stream of two audio channels in stereo-configuration.

Envisioned Implementation
-------------------------
A new setting denominating the desired number of audio-streams is added to the config. Through the complete audio path (except for the stream-blanker audio-sinks), all interaudio-Elements are added as many times as required (for a 4 stream configuration, 4 interaudio-Elements are added). Technically each source can thus provide all 4 Streams and all sinks receive 4 Streams.

The Audiomixer-Class creates 4 audiomixer-Elements, each connected to the associated input- and output-streams.

Each Sourcing-Script now *needs* to provide 4 Stereo-Audio-Streams together with its raw-video-stream. It is then up to the author of the source-Pioelines to correctly map the source-audio-Streams.

If time is left, a more sophisticated configuration for the audiomixer can be envisioned, which would allow to exactly configure which stream from which source is added to the mix. This would be a separate story and should not implemented within this story, because this story on its own can be used to fulfil the requirements.

For example each of those setups are possible:
> Two Cameras on two Decklink MiniRecorders, No embedders
>> The first and second audio-streams are fed into the first camera as left & right, the third and fourth audio-streams are fed into the second camera
>> The two sourcing-Scrips map the left & right channel of the camera-audio to stereo-channels 1-2 and 3-4 respectively
>> The first video-source-script thus provides video-1, audio-1, audio-2 (and silence on audio-3 and audio-4)
>> The second video-source-script then provides video-2, audio-3, audio-4 (and silence on audio-1 and audio-2)
>> The audiomixer now combines those audio-streams into the desired 4-stream audio output

> 1+n Cameras on 1+n Decklink MiniRecorders, With embedders
>> All audio-streams are fed into an embedder positioned after the first camera.
>> No audio is fed into the second camera
>> The first video-source-script thus provides video-1 and audio-[1..4]
>> The second video-source-script then provides video-2 (and silence on audio-[1..2])
>> The audiomixer now combines those audio-streams into the desired 4-stream audio output

Required Changes:
- [x] add a config-option and example-config to default-config.ini
- [x] extend avsource.py / tcpavsource.py to provide one interaudiosrc for each configurd stream.
- [ ] add tests that check the behavior with none, 0, 1, 2 configured streams.
- [x] extend audiomix.py to provide one interaudiosrc+audiomixer+interaudiosink for each configurd stream. add tests.
- [x] extend streamblanker.py to provide audiomixer for each configurd stream. add tests.
- [x] extend avpreviewoutput.py, avrawoutput.py to provide one interaudiosink for each configurd stream. add tests.

- [ ] extend voctogui to handle the multiple audio-tracks

- [x] decide what to do with decklinkavsource.py - gstreamer does support multiple channels since 1.12.3
- [x] extend decklinkavsource.py to support building a stereo-stream from a single source channel

- [x] add example-script to source 3×mono from media.ccc.de to audio-streams 1..3 (as 3× stereo)
- [ ] add example-script to source stereo from decklink-sdi to audio-stream 1 (as 1× stereo)
- [ ] add example-script to source stereo from decklink-sdi to audio-streams 1 & 2 (as 2× mono)
- [ ] add example-script to source stereo from decklink-sdi to audio-streams 3 & 4 (as 2× mono)
- [ ] add example-script to source 4×mono from decklink-sdi to audio-streams 1..4 (as 4× mono)
- [x] extend cm to allow configuring the cam-source-scripts to map stereo-input ("without-embedder mode") to desired channels 
- [x] extend cm to allow configuring the cam-source-scripts to map multi-channel-input ("with-embedder mode") to desired channels

**Comment by derpeter** [comment]
Can you provide some details what needs to be done in the core to pass more audio streams through the pipline?

**Comment by MaZderMind** [comment]
Zwischenstand: Es gibt Code in https://github.com/voc/voctomix/compare/master...MaZderMind:feature/154-multiaudio
Dieser tunnelt erfolgreich n Stereo-Audiospuren von TCP-Quellen durch alle Mixe und Outputs. Der Streamblanker mappt das Pause-Audio auch korrekt auf alle Spuren.

Defekt sind derzeit die internen Decklinkquellen, weil deren Output anders heißt. Außerdem können die decklinksourcen bis Version 1.12.3 nur 2 Kanäle. Zum Vergleich die für uns relevanten Versionen:
- Erforderlich 1.12.3
- VOC 1.6.3
- Debian jessie: 1.4.4
- Debian stretch: 1.10.4
- Debian buster: 1.12.3
- Ubuntu trusty (aktuelles LTS): 1.2.4
- Ubuntu xenial: 1.8.0
- Ubuntu zesty: 1.10.4
- Ubuntu artful: 1.12.3

d.H. dass wenn wir echten mehrspur-Support (bis zu 16 Spuren auf einem SDI-In) haben wollen, dann müssen wir *entweder* Support mit allen aktuellen OSen einstellen *oder* beide Modi supporten.
Außerdem müssen wir uns ne ne neue Version backporten und ausgiebig testen.

Alternativ gibt's multiaudio-Support mit den internen decklink-Quellen nur, in dem man je 2 Kanäle je SDI annimmt und entsprechend zusammenklebt.

**Comment by MaZderMind** [comment]
Discussion pointed towards the following solution:
- keep supporting gstreamer <1.12.3 when `audiostreams=1` is configured. This keeps compatibility for probably all users except c3voc
- apply the required patches to the VOC-Version (1.6.3) if possible and run congress with that

**Comment by MaZderMind** [comment]
@dedeibel probably this patch would be enough: https://github.com/GStreamer/gst-plugins-bad/commit/e8e531ee12efc687f427a9596c824d63a219eb52#diff-28b5504c8d8bfd033ed45b9298a56e41

**Comment by MaZderMind** [comment]
fixed in #173
