### ISSUE TITLE
Share lib/config.py, lib/loghandler.py and lib/args.py between core & gui

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#146]
When keeping the root-project structure as is (voctocore in `/voctocore/voctocore.py  snd voctogui in /voctogui/voctogui.py`) I see, checking on pythons import method, the follow options:

1. a folder in `/shared` which is symlinked into both projets
2. a git-submodule based approach with the shared files in their own repository
3. modifying `sys.path` to contain `../shared` on startup
4. merge voctocore into one folder with two entrypoint `.py` files
5. merge voctocore and voctogui into one `.py`-file

2 is not an option for me, because the files do not constitute a project of their own
1 would be easy but might be problematic in packaging, although there the symlinks could be replaced by a copy to re-gain individual packages
3 would be the least messy solution but also could raise problems in packaging. maybe @h01ger can elaborate on these option.
4 would need a modification of the repository-layout to have both, voctocore and voctogui in one folder, leaving `/voctocore.py`, `/voctogui.py` and `/libs/…`, probably with distinct `./libs/core/…` and `./libs/gui/…` for the classes only used by one of the two.
5 would go a step further, it all down to one application (`./voctomix.py --core` and `./voctomix.py --gui`, probably)

I'm currently quite unsure which solution might be the best one, so I'll leave this ticket open for discussion.

**Comment by dedeibel** [comment]
Thinking out loud…

1. I think this could work with little effort on the dev. Packaging might have to change.

But considering UI and core seem more like separate applications I rather think the right thing to do would be to create a _voctomix-lib_ package on it's own. But if I interpret your comment correctly - it does not seem enough code to be worth the hassle. Understandable.

2. Should solve the problem on the developer side, maintaining the repo seems work. _submodules_… they can be annoying.

3. I don't know much about python conventions but it just feels strange to grab upwards out of your directory. I'd prefer the linking into it, only considering those two.

4. / 5. I think this would be the wrong path I don't see why you would want to do this. I like that they are separate.


I think I would try 1. the linking and copying for packaging, considering how small the files are. If the shared parts grow, I would try to aim for a _voctomix-lib` python package.

**Comment by fightling** [comment]
I had a similar approach for the configuration in feature/onepipe branch. Just if you like to take a look then look into /vocto/config.py. It's not the full job but you might see what it looks like. The code is less and in my opinion more readable and you prevent inconsistent default values too!

But till now I didn't thought about doing this with args and loghandler. But seems plausible.
