### ISSUE TITLE
Streaming to YouTube Live

### ISSUE THREAD

**Issue by crossan007** [voc/voctomix#162]
Create example script for YouTube live

**Comment by CarlFK** [comment]
Here is a pointer to what was used in production 

https://github.com/CTPUG/pyconza2017-video/blob/master/inventory/group_vars/all.yml#L48
 location: "rtmp://a.rtmp.youtube.com/live2/x/{{ youtube_auth }} app=live2"

**Comment by crossan007** [comment]
Is this an Ansible config?   I've really got to learn Ansible - this looks like gold.
