### ISSUE TITLE
Change verbal descriptions for composition modes in voctogui

### ISSUE THREAD

**Issue by benjaminwand** [voc/voctomix#182]
Terms like 'side-by-side-preview' don't belong into a GUI. 

Suggestion, rename (in the voctogui):

'Side-by-side-preview' -> 'Supersource'
'Side-by-side-equal' -> 'Side by side'

IMHO 'Fullscreen' and 'Picture in picture' are fine words for that purpose.

**Comment by fightling** [comment]
Names are changed completely in voctomix2 now and they can be named freely. Think this solved.
