### ISSUE TITLE
voctogui: not have the conference logo in the lower right corner of side-by-side-preview if the conference logo is on the upper half of the lectern

### ISSUE THREAD

**Issue by benjaminwand** [voc/voctomix#183]
This is a problem we had before with the black magic mixer setup and now it made its way to voctomix: at congress (and other events), the conference logo is on the lectern. If the logo is in the lower right corner of side-by-side-preview that means the camera angel is limited to do a very close close-up of the speaker if the speaker is at the lectern, because 1.5 or 2 logos directly on top of each other look really stupid. But often the speaker moves a bit and then it would be useful to zoom out just a bit.
Suggestion: move the logo elsewhere. Top right corner or something.

**Comment by saerdnaer** [comment]
Sorry, but this issue has noting to do with the software itself, but with the designer of the background image.
