### ISSUE TITLE
voctocore.py switching between different view modes automatically ??

### ISSUE THREAD

**Issue by hayden-t** [voc/voctomix#184]
If it is just running by itself , it switches between cam 1, cam 2 v pic in pic, side by side etc, as if you are clicking through the gui buttons, but the gui isnt running and no commands are being sent to controlserver.

Its like some kind of demo loop, I just installed it, is this normal, how do you disable it ? it still happens even with the gui running.

Thanks

**Comment by MaZderMind** [comment]
The core isn't doing this on its own. I guess you still have an instance of https://github.com/voc/voctomix/blob/master/example-scripts/control-server/demo-cycle-modes.sh running somewhere?

Probably started by https://github.com/voc/voctomix/blob/master/example-scripts/misc/demo-local.sh

**Comment by hayden-t** [comment]
cheers, thought it was a bit weird and that it might be something like that, thanks.
