### ISSUE TITLE
additional dependencies for example scripts

### ISSUE THREAD

**Issue by hayden-t** [voc/voctomix#186]
Hi, just got it running on a fresh install of Debian 9, thought id mention some additional packages i needed that weren't mentioned in the install guide:

FFmpeg (now in debian repo)
Netcat (for nc command)
gstreamer1.0-vaapi (for vaapi preview option)

**Comment by derpeter** [comment]
@h01ger i see https://packages.debian.org/stable-backports/voctomix here that this deps also are missing in the vocotomix debian package, what are your toughts on adding those?

@hayden-t in fact non of the deps you mention are mandatory to run vocotmix but i agree we should mention them somewhere. Would you mind to make a suggestion where you would like the information to be ? Maybe even a pullreuqest ;-)

**Comment by a-tze** [comment]
Maybe they should be referenced as "Suggests" or "Reccommends". They are actually no dependencies because the software would run without them, but providing the tools necessary to make a quick start with the example scripts is of course very nice.

**Comment by h01ger** [comment]
voctomix already suggests this:

Suggests: fbset, gstreamer1.0-libav, python3-pyinotify, rlwrap

I dont see whats missing exactly + where.

**Comment by hayden-t** [comment]
corrected title and made pull request: https://github.com/voc/voctomix/pull/191
