### ISSUE TITLE
voctocore ControlServer schedules idle tasks when there is nothing to do.

### ISSUE THREAD

**Issue by jhenstridge** [voc/voctomix#19]
The ControlServer class in voctocore unconditionally schedules an idle task that will be called repeatedly even when it has nothing to do.  This means the event loop can never sleep, and even when there is work to do it will waste time calling into this code.

If command processing needs to happen in an idle task, it would be better to schedule the callback when commands have actually been received, and to stop the idle task when there are no more commands to process.

**Comment by MaZderMind** [comment]
Hum. I'm not that familar with GLib. Actually I'm just hacking my way around it. How would one implement this the correct way?

`on_loop` would return False when nothing more is to be done while `on_data` and `on_write` would schedule calls to `on_loop` again? I'd be very happy for a PR and would certainly merge that.

**Comment by jhenstridge** [comment]
That is roughly the way it could be done.  An alternative would be to throw out the current logic and use Twisted.  I assume its Python 3 port has come along far enough to handle a simple line oriented TCP server and glib main loop integration, but I'd have to check that.

If Twisted is out, I can have a look at updating the existing code.

**Comment by MaZderMind** [comment]
Hmmm I'm not really knowledgeable regarding twisted but my gut feeling is that loading a huge library like python twisted into the core is not the best thing to do, just to handle the little command server. On the other hand I'm already loading GObject and GStreamer and Gdk which are indisputable huge libraries in its own.

What would be the benefits of using twisted over the current (or a similar) logic?

**Comment by jhenstridge** [comment]
I agree that Twisted is a large library.  However, much of that size comes from implementations of the various network protocols: the core of the package is not particularly large.

The main reason I mentioned Twisted is that I know it has solved many of the problems to do with implementing asynchronous network protocols.  I wouldn't be surprised if the busy-wait problem I identified is the only one either: I see a bare try/except block in the on_data method, which also looks like a bit of a red flag.

A Twisted implementation would look something like:

1. update the top level voctocore.py script to install Twisted's gireactor implementation: this allows Twisted to function inside an application using the glib main loop.

2. Write a Twisted protocol class that implements the control server protocol.  This can easily be done using the LineOnlyReceiver helper class:

 https://twistedmatrix.com/documents/current/api/twisted.protocols.basic.LineOnlyReceiver.html

 Using this class, most of the current code in on_loop can be moved to an override of the lineReceived() method, and responses sent back with sendLine().

3. Use the Twisted API to listen on the socket and hook up the protocol for incoming connections.

**Comment by MaZderMind** [comment]
That really sounds like something we want to use. The current API is -- as you pointed out -- more or less hacky. I'd be very happy to receive a PR for that, as you seem to know what you're talking about.

**Comment by jhenstridge** [comment]
Okay.  I'll see if I can put something together.

**Comment by jhenstridge** [comment]
It looks like this same issue exists in the client code in voctogui.  The existing pull request is still a net improvement though, so it's probably better to handle voctogui in a second merge.

**Comment by MaZderMind** [comment]
I think this has been fixed in #41
