### ISSUE TITLE
Scripts in voctocore/scripts are dependent on running with a PWD==voctocore/scripts

### ISSUE THREAD

**Issue by mithro** [voc/voctomix#2]
It would be good if they ran independent of the PWD when launched.

See following for possible solutions;
 * http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
 * http://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself

**Comment by MaZderMind** [comment]
this is still true for some of the scripts, but as they are more of a documentation part then actual code, I don't want to clutter them with complex bash constructs.
