### ISSUE TITLE
ControlServer will run arbitrary methods on the ControlServerCommands object

### ISSUE THREAD

**Issue by jhenstridge** [voc/voctomix#22]
This seems pretty unsafe for an unauthenticated network process.  I was able to effectively disable the command server until voctocore was restarted as follows:

    $ telnet localhost 9999 
    Trying 127.0.0.1...
    Connected to localhost.
    Escape character is '^]'.
    __init__ foo
    None
    get_audio
    error 'str' object has no attribute 'amix'

This change affected future connections to the command server too:

    $ telnet localhost 9999 
    Trying 127.0.0.1...
    Connected to localhost.
    Escape character is '^]'.
    get_audio
    error 'str' object has no attribute 'amix'

If you're going to delegate commands directly to methods, perhaps prefixing the methods would be appropriate.  For example, if the user runs the `get_audio` command, the `cmd_get_audio` method is run.

**Comment by MaZderMind** [comment]
Actually the ControlServerCommands is meant to be like a Prefix - every method on here should be runnable via the control-protocol, except `__init__`. For this reason i would implement a filter for methods starting with `_` which would allow to use "private" methods following the python conventions.
