### ISSUE TITLE
Warn on incompatible Video-Input-Formats

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#25]
The Core should catch the negotiation signal when a source tries to connect and compare the incoming caps with the configured caps. Currently, when putting in a invalid video format, the source-pipeline just stops without a warning (the mixer remains functional but it isn't obvious why a specific video is not working):

![screenshot from 2015-11-17 08 37 18](https://cloud.githubusercontent.com/assets/142237/11205236/74a883d0-8d06-11e5-8222-0cee31b87eb5.png)

**Comment by jhenstridge** [comment]
Would it make sense to stick a decodebin into the pipeline and support formats other than raw video over the wire?

Capture hardware like HDMI2USB produce MJPEG in certain modes, so if there is a choice between decoding those frames at the capture end or the mixer end, being able to do so on the mixer would seem preferable.

**Comment by derpeter** [comment]
We used vocotomix with epipahn vga broadcaster as slide grabber. This device produces MJPEG or H264 streams. Conversion is done before feeding it to vocotomix. Not sure if there would be a CPU load benefit from doing it in the core but it seems to raise the complexity. Do you see any advantage in doing it in the core except less external encoding calls?

**Comment by MaZderMind** [comment]
Yes, it was a design goal to not have encoder/decoder in the core but as external processes. This allows killing and restarting them without interrupting the core. Decoder and Encoder are complex pieces of software with many, many parameters, that may be tuned or changed, depending on the situation. For this reason I do not want to have them in the core.

For example during our last test-run we had issues with the way our slides-mjpeg-decoder produced silence, so we restarted it multiple times while the stream and the recording kept on running. This would not be possible if the problematic part would be part of the core.

Another example is gracefully handle broken 16:9/4:3 sources. On some conferences we have multiple versions of the slides-deocder which can handle cropping and scaling and depending on the situation we use the one or the other script to read from the mjpeg-source and push into the core.

**Comment by jhenstridge** [comment]
Assuming the central mixing host can handle it (which it hopefully can with simple codecs), the obvious benefit is greatly reduced network traffic.

**Comment by MaZderMind** [comment]
network traffic via loopback is nearly free, compared to the tasks of encoding to h264 or something. We usually have the conversion-tasks like the one that converts from mjpeg to raw-video running on the same host.

**Comment by CarlFK** [comment]
seems like this could be addressed with something like this running on the core box:
  
gst-launch-1.0 
tcpclientsrc host=10.0.0.1 port=10000 
decodebin
tcpclientsink host=127.0.0.1 port=10000

Does this need to know the caps the server is expecting?
video/x-raw,format=I420,width=1280,height=720,framerate=30000/1001,pixel-aspect-ratio=1/1 

that should/could be contained in the incoming stream, right?
