### ISSUE TITLE
Simplify Multichannel-Audio-Code

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#251]
Currently the Multichannel-Audio-Code is built around the original limitation of the inter* elements, which could only carry 2 channels. Therefore we have all Elements working with audio configured for 2 channels and multiple times (` audiostreams`-times).

Since we no longer rely on them, we can simplify the Multichannel-Audio-Code so that after the Sources, all Pipeline-Elements use a single Stream of n channels. The Sources would then have the obligation to map their input-format to these n channels.

**Comment by fightling** [comment]
solved in voctomix2
