### ISSUE TITLE
Is 1080p60 impossible?

### ISSUE THREAD

**Issue by gnarr** [voc/voctomix#256]
Hi!
I have been trying to integrate voctomix into my workflow. I love the simplicity and power, but I'm having trouble mixing 1080p 60fps.
Everything works smoothly up to 41fps, but as soon as I go over 41fps voctomix seems to ignore my input.

Is this a known issue or is there a known workaround?

**Comment by CarlFK** [comment]
What CPU?
OS
sources and sinks?

**Comment by gnarr** [comment]
I just figured out I had left in a source with video_mode commented out. Changed it from ";video_mode = 1080p60" to "video_mode = 1080p60" and now everything is working.

Sorry for the trouble and thanks for the help :)

**Comment by MaZderMind** [comment]
@Gnarr it would still he nice to share which system you are operating on and, if possible, add your setup to the Wiki: https://github.com/voc/voctomix/wiki/CPU-works-works-not-Table

**Comment by gnarr** [comment]
@MaZderMind Done :)
It's an i9 7900x running Ubuntu 19.04 with 2 sources and 1 sink.

The final setup will run on AWS. I will add more info once it is running.
