### ISSUE TITLE
Program installs on debian buster but crashes

### ISSUE THREAD

**Issue by desputinski** [voc/voctomix#270]
Hi,
is vectomix compatible to debian buster?
I installed it yesterday successfully, but when I run:
> ./voctocore/voctocore.py -vv
The graphical environment (xfce) crashes.

Does anyone here know what the problem might be?

**Comment by CarlFK** [comment]
On Thu, Jan 9, 2020, 11:46 PM desputinski <notifications@github.com> wrote:

> Hi,
> is vectomix compatible to debian buster?
> I installed it yesterday successfully, but when I run:
>
> ./voctocore/voctocore.py -vv
> The graphical environment (xfce) crashes.
>
> Does anyone here know what the problem might be?
>

This installs buster and vocto
https://debconf-video-team.pages.debian.net/ansible/usb_install/usb_quick_start.html

Give that a try, please report back.

**Comment by derpeter** [comment]
@desputinski can you explain what you mean be xfce crashes? The voctocore has no gui component so interaction with xfce should not happen.
Depending on your config and the hardware in your machine voctocore can saturate your CPU which may lead to an unresponsive desktop.

**Comment by desputinski** [comment]
@CarlFK  Thank you for the hint. I will try to install according to that link next time when I'm at that machine...
@derpeter Hm, I'm not sure. As I said: I ran ./voctocore/voctocore.py -vv, black screen for a second and then the xfce-login-screen reappeared. 
So if there is no gui I start the browser? I thought there is some graphical interface to switch during the recording e.g. between speaker and presentation...

**Comment by derpeter** [comment]
no there is a gui, its next to voctocore in the voctgui folder. But you need to start that separate.
You start first the core and than the gui. Its a client server architecture so you can run both part on different machines. 

You should check your syslog and where ever XFCE writes is errors to to see why XFCE dies.
