### ISSUE TITLE
Space/Return sets stream live

### ISSUE THREAD

**Issue by QbDesu** [voc/voctomix#275]
In any situation where you wouldn't trigger another action(transistion/cut usually) pressing space or return causes the stream to be set to live.
If i'd have to guess, I guess it happens because of GTK stuff, that the live button is permanently selected/focused as part of GTK built-in features and pressing space/return just triggers the currently focused button in GTK.
EDIT: Looking into the code I saw that you even tried making the button non-focusable but it didn't help. Strange..

**Comment by Kunsi** [comment]
fixed in #320
