### ISSUE TITLE
Configurable Scene-Buttons for GUI

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#29]
In #26 and #27 several restrictions on the Video-Selection logic were requested in order to allow simpler Switching between what I would call Scenes, for example
- Slides as A and a Cam as B in Side-By-Side or Picture-in-Picture mode
- Slides in Full-screen
- Cam  in Full-screen

Currently, switching from "Cam in Full-screen" to "Slides as A and a Cam as B in Side-By-Side" requires two actions and would result in twitchy video. For the very same reason in #11 I added a special To-Full-screen-Button.

To fulfill the various requirements for scenes I'd suggest to add configuration options which allow various scenes to be pre-defined. I could imagine that the four composition-buttons would then be the default configuration.

This could, for example, look like this:

``` ini
[mix]
scenes=side-by-side-preview,closeup-in-slides

# example for the default side-by-side-preview scene
# which only changes the placements of a and b sourde
# but leaves the a/b selection intact
[side-by-side-preview]
asize=1024x576
apos=12/12
bsize=320x180
bpos=948/528

# example for a special closeup-in-slides scene
# which also changes the a-soure to grabber which
# automatically enforces the b-source to be one of the
# cameras
[closeup-in-slides]
a=grabber
;b=cam1
asize=1920x1080
apos=0/0
bsize=320x180
bpos=948/528
```

Depending on how mighty one wants to get here, also compositions with more then two sources, other parameters like alpha channels and even animations based on [GstInterpolationControlSource](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-libs/html/GstInterpolationControlSource.html) and [GstDirectControlBinding](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-libs/html/GstDirectControlBinding.html)…  might be configurable. One could also try to express the sizes in formulas like `bsize={iwidth*1/10}x{owidth*16/9}`.

I'd like to open this as a discussion if this would solve #26 and #27 in a less hardcoded way – and if this is desirable.

**Comment by derpeter** [comment]
I think this is a step in the wrong direction. We should first figure out what are usefull defaults bevor adding complexity. I don't believe that there are that many usefull scenes and leaving the user with configuration file is only halfe of the deal. It needs to be refelcted by buttons that work intuitve for the operator.

**Comment by MaZderMind** [comment]
Parts of this feature can be re-used, but the interface-idea will not be implemented.
