### ISSUE TITLE
voctogui is hanging out

### ISSUE THREAD

**Issue by arvindveeramani** [voc/voctomix#290]
am running my voc2gui in x2go client xfce but the voc2gui is hanging whenever its opening..[
![Screenshot (2)](https://user-images.githubusercontent.com/73211895/108984764-4d6c4a00-76b6-11eb-8368-1f24e2df3c22.png)
](url)

**Comment by derpeter** [comment]
Hey, this looks like the UI is not able to get the preview videos. Or maybe the gui is not able to draw them, i guess no one tried this before on windows.  If you click the symbol next to the snail on the bottom of the window you should the the ports for the previews. Try to play the preview videos with ffplay or mpv e.g. ffplay tcp://localhost:130000 

Also run the core with -vv it will most likely complain about somehting. 

Please upload your config of gui and core so we see what we are wokring with here

**Comment by arvindveeramani** [comment]
here am attached my config and issue ss.


![Screenshot (3)](https://user-images.githubusercontent.com/73211895/109135630-4b20f300-777d-11eb-87ed-61973add048b.png)

**Comment by arvindveeramani** [comment]
[gui config.txt](https://github.com/voc/voctomix/files/6042072/gui.config.txt)
[core.txt](https://github.com/voc/voctomix/files/6042073/core.txt)

**Comment by arvindveeramani** [comment]
![Screenshot_2021-02-26_11-12-59](https://user-images.githubusercontent.com/73211895/109267995-dc4aa500-7823-11eb-9fc0-0cdc66e621aa.png)


actually am tried this in linux only not in windows sir.,and am already shared the config files in above..

**Comment by arvindveeramani** [comment]
![Screenshot_2021-02-26_11-18-39](https://user-images.githubusercontent.com/73211895/109268371-6a269000-7824-11eb-8191-cae7bc6474d5.png)
it shows warning like this..

**Comment by arvindveeramani** [comment]
[
![Screenshot_2021-02-26_11-20-05](https://user-images.githubusercontent.com/73211895/109268495-9a6e2e80-7824-11eb-9679-7c2d2f10512f.png)
](url)

and am received warning like this

**Comment by derpeter** [comment]
So config looks good so far. The warning is not a problem here, it basically tells you about an logical problem with the config but nothing that would prevent it from work. From what i can see on the screenshots i would still assume to problem is in the core.
Could you please also provide the complete log output (the one from the last screenshot).
I would guess the pipline is not starting completely. by the way are you using the code shipped with ubuntu or from the git?

**Comment by derpeter** [comment]
closed because of inactivity, please reopen if needed
