### ISSUE TITLE
voctomix depends on ffmpeg but only avconv is easily available

### ISSUE THREAD

**Issue by mithro** [voc/voctomix#3]
It appears that a lot of the scripts require ffmpeg to operate. Ubuntu by default only has avconv which is mostly compatible. In theory both ffmpeg and avconv have the same command line arguments.

It would be good if the scripts did something like;
```shell
if ffmpeg; then
  AVCONV=ffmpeg
else
  AVCONV=avconv
fi

$AVCONV blah blah
```

There should probably be some check that ffmpeg or avconv is installed too.

**Comment by mithro** [comment]
It looks like my avconv version doesn't have the aresample filter;
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/usr/local/google/home/tansell/31c3-sendezentrum-1013-de-Methodisch_inkorrekt_Die_falsche_42_hd.mp4'
:
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Methodisch inkorrekt!: Die falsche 42
    artist          : Nicolas Wöhrl, Reinhard Remfort
    album           : Chaos Communication Congress 2014 (31C3)
    encoder         : Lavf55.33.100
    genre           : Podcast
    copyright       : Licensed to the public under http://creativecommons.org/licenses/by/3.0/de
  Duration: 01:38:43.92, start: 0.000000, bitrate: 4308 kb/s
    Stream #0.0(und): Video: h264 (Main), yuv420p, 1920x1080 [PAR 1:1 DAR 16:9], 4141 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc
    Stream #0.1(deu): Audio: aac, 44100 Hz, mono, fltp, 160 kb/s
[AVFilterGraph @ 0x24644c0] No such filter: 'aresample'
Error opening filters!
```

**Comment by saerdnaer** [comment]
As far as I know, we have an own debian repository which contains ready to use ffmpeg packages. Just ask Florolf oder Mazermind via IRC.

**Comment by MaZderMind** [comment]
on one hand, the 'scripts' are only development-and-debug tools and *maybe* part of the documentation, so actually voctocore is not dependent on ffmpeg.

on the other hand, I would prefer ffmpeg over avconv and won't discuss this here but rather on the irc, so I'm closing this issue.
