### ISSUE TITLE
Wish: all the input's muxed into one multi track output stream 

### ISSUE THREAD

**Issue by CarlFK** [voc/voctomix#314]
I would like to save all the input streams to disk for editing later (sometimes the live edits aren't good and it is worth the effort to fix.)

I think/hope it would be better if all the tracks were in one big file as opposed to each input having it's own file.

if all the streams were muxed and available on a port, I could hook up a client that saved them to disk.

**Comment by MaZderMind** [comment]
You can do that in a script reading from multiple Ports. See https://github.com/voc/voctomix/blob/main/example-scripts/ffmpeg/record-mixed%2Bslides%2B8channel-audio-ffmpeg-segmented-timestamps.sh for an example which records mix-out, slides and 8ch Audio into mpeg-ts segments usable with [fuse-ts](https://github.com/a-tze/fuse-ts).

**Comment by MaZderMind** [comment]
Additionally you can use a script like https://github.com/voc/voctomix/blob/main/example-scripts/control-server/generate-cut-list.py to also record the cut-commands and re-create a projectfile of your favourite Video-Editor from that.

**Comment by danimo** [comment]
Note: That method of ISO/multitrack recording does not guarantee a that the timestamps will match up. It was good enough for us as we only record the slide input, but with proper ISO recording, this might turn into an issue.
