### ISSUE TITLE
voctocore: newer python3 versions don't have SafeConfigParser anymore

### ISSUE THREAD

**Issue by jane400** [voc/voctomix#330]
https://docs.python.org/3.9/whatsnew/3.2.html?highlight=safeconfigparser#configparser

Trying to get voctocore via dockerfile on ubuntu:noble running results in: 
```
  File "/opt/voctomix/vocto/config.py", line 5, in <module>
    from configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
```

this issue is just leaving notes for myself later, i'm currently on a cursed setup and am applying hacks (aarch64/pmOS)

**Comment by Kunsi** [comment]
Interesting, this did not occur when testing on my arch linux machine 🤔
