### ISSUE TITLE
Cropping of PIP

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#36]
for some picture-in-picture / side-by-side-preview constellations it would be nice to be able to crop the small picture so a custom size, for example to a square.

cc @danimo

**Comment by MaZderMind** [comment]
If we configure the PIP to be cropped to square, what would would happen when the operator selects to show the slides as PIP in the camera? Should Voctomix crop the slides, too or should it detect them as slide-source and not crop them?

**Comment by bjoern-r** [comment]
the cropping should be associated with this output mode and position. Whatever is put to this "slot" should be cropped.

**Comment by derpeter** [comment]
I think it would be enough to set per input. There is no much benefit to reconfigure it during a lecture.
As an alternative there could be a crop button next to the preview.

**Comment by MaZderMind** [comment]
This will be implemented in #29
