### ISSUE TITLE
GUI Slowdown due to alsa-sink

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#37]
It seems, the GUI previews slow down after some time on mixer-laptop5 and restarting the UI fixes this.

**Comment by MaZderMind** [comment]
since e2969b87441a46fe0c017f1f29bb7ec3f4fce585 it is possible to select between different video subsystems. It would be interesting if the issue arises with all of them.

**Comment by xfxf** [comment]
The issue appears to happen with both xv and the default gl.
However, when using the intel driver on latest Ubuntu, when using gl, vocto GUI ends up causing a segfault in intel_drv.so and logging out the user.  I am instead using xv, and problem is not present (but the GUI slow down still occurs).

For me, when the GUI slows down - the little preview windows on the left are still full speed. It's only the main screen which is slow.  Restarting the GUI fixes this.

**Comment by MaZderMind** [comment]
@derpeter can you acknowledge the slowdown happening only (ore mostly) on the main-mix display?

There are two things that differ between the preview video-display and the main-mix display:
1. the main-mix is bigger, so more data needs to be transferred from the cpu to the graphics card (and through x and the driver)
2. the main-mix is usually also connected to alsa for audio playout. This can be disabled [in the config](https://github.com/voc/voctomix/blob/master/voctogui/default-config.ini#L13). If alsa would block, this would also block the main-mix display.

**Comment by xfxf** [comment]
I'm now testing this with alsa audio output disabled.

**Comment by bjoern-r** [comment]
I can acknowledge that the slowdown only affected the main-mix display during the 32c3.

**Comment by derpeter** [comment]
I'm not 100% sure if it has never happend to the other previews but during c3 i only saw it on the big preview.

**Comment by xfxf** [comment]
I've ran the UI now for 12 hours straight with the audio monitoring disabled, and I am yet to see a slowdown.  Normally this happens after 2-3 hours.  I've just restarted core/gui, will let it go for another ~12h today and report back.

**Comment by MaZderMind** [comment]
for the moment I'll disable audio out in the default settings

**Comment by MaZderMind** [comment]
Thinking another night about it, it seems plausible that when audio-out is enabled this pipeline chooses the alsa clock to be its pipeline-clock. Therefore this pipeline will have different clock & jitter characteristics (depending on the hardware clock inside the soundcard) then the rest of the system which would lead to the exact behavior described above.

As a solution we should force the same system-clock on all pipelines. We could even use the Core's network-clock (see #46) and have the gui sync onto the master.
