### ISSUE TITLE
Sources for voctomix gstreamer apt repository are missing.

### ISSUE THREAD

**Issue by micolous** [voc/voctomix#40]
Currently voctomix's apt repository for gstreamer is built against deb-multimedia which is unacceptable to me for a variety of reasons which I won't delve into here.  This also precludes use of the repositories from Debian derivatives.

I was hoping to be able to rebuild them against a different set of repositories, but there is no published repository on github.com/voc which describes the source packages used.  These appear to be built entirely offline, so there is no way for me to send you patches which fix problems.

There should be a repository with the Debian package metadata in it, so I can build these and patch these easily.

This is something I would be happy doing in a VM, but then the high CPU requirements of voctomix preclude operating it on anything but bare metal.

**Comment by a-tze** [comment]
Building against deb-multimedia was no easy choice, but less evil for us than building against avconv. The only alternative that came into our mind is building against our own ffmpeg build, but that build is not vanilla and includes libs that also make it non-redistributable.

Which kind of package metadata do you refer to? The package repository should contain all usual metadata and also the sources used to build the packages.

**Comment by micolous** [comment]
I notice that [the directory listings are now turned on](https://c3voc.de/voctomix/dists/jessie/non-free/source/), that's a whole lot better, thanks!  I can now see what is in the repository without trying to also have the corresponding binaries in there, or add it to my apt sources.

The contents of `*debian.tar.xz` should be in a source control repository, one for each of the packages.  There should be a script which grabs the `orig.tar.xz` files, that can be from the upstream project or your own mirror -- these would correspond to upstream's source tarballs.

This should be split by distribution tag, so you have a git repository like `debian-packages.git/jessie/non-free/gstreamer1.0/1.6.1/`.  When there is a new package version pushed (eg: 1.6.1-deb4 vs. -deb5), this gets tagged in the git repository.

There's probably a fancy proper Debian way to do this which meets this objective.

**Comment by MaZderMind** [comment]
You could just use Debian Sid  which has gstreamer 1.6.2 packaged or Ubuntu Wily which has gstreamer 1.6.0.

**Comment by micolous** [comment]
Yeah, I'm on Ubuntu Trusty so going to Wily is probably an option, just hoping it doesn't hose my laptop in the process :)

Not something I will be able to do soon due to a slow internet connection on a short night.  I will just get it running on a much faster internet connection instead in the morning.

**Comment by MaZderMind** [comment]
I updated the Readme to point to Wily & Sid as an go-to option: 84e591a7e5301e9841da474d22b0d6c9f6c1fde5

Do you feel this fixes your issue or would you suggest us to to something else?

**Comment by micolous** [comment]
Yeah, I think that resolves the issue, and now that the directory listings are on that's good.  Thanks!

**Comment by a-tze** [comment]
Just a quick note: the gstreamer packages are not versioned since they have been taken unmodified from the current Debian testing. The only difference is the compile-time presence and therefore automatic binary package dependency on the deb-multimedia ffmpeg. So if you want to build it against another ffmpeg version you can either apt-source and build the source packages from the package repo or directly from Debian testing, but it's quite a lot of work though.
