### ISSUE TITLE
Configure Audio-Source

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#63]
There should be a configuration option to select the Audio-Source. If this option is present, the GUI should hide the Audio-Source selector and the API should not accept commands to select a different source.

**Comment by derpeter** [comment]
As an alternative to hiding the gui element the setting could be written to the config. This could be used for all runtime decisions, therefore vocomix would come back with the the same picture setting after a restart (or a crash). This could also be a separat config file.

**Comment by MaZderMind** [comment]
@derpeter to that are absolutely two features with different semantics.

The last state should be a different file and it would need a way to be reset, when the config changes. we should discuss this in a separate issue.

**Comment by MaZderMind** [comment]
fixed in #111
