### ISSUE TITLE
Example-Script to record all incoming Audio-Tracks

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#64]
The Voctocore should have a All-Audio-Out port which provides an MKV stream with all Audio-Tracks of all sources for backup recording.

There should be a Script to record all Audio-Tracks of all sources into a single .ts file. There should also be a segmenting version of it.

**Comment by derpeter** [comment]
Alternative: record all audio streams to the master recording and make the tracker aware of the backup tracks. Probably both ways could be implemented

**Comment by a-tze** [comment]
I don't get this one. What do you mean with sources.. the inputs before they get edited in voctomix? What component will throw them into one datastream?

Maybe it is better to have voctomix build something like an audio aux out with all input audio tracks assembled.

**Comment by derpeter** [comment]
in this context sources are the MKV with a and v in it. Masterminds suggestion is to record all incoming audio streams. There are already outputs so you can write a simple script that does that.

**Comment by MaZderMind** [comment]
@a-tze voctomix provides mirror-ports which mirror all incoming video and audio. one mirror-port per configured source (usually 3: cam1, cam2, grabber).

One can write an (example)-script which takes the audio-streams from all three mirror-ports and creates one recording with just the audio.

**Comment by a-tze** [comment]
Ah, so there is already something like an aux per input, great.

**Comment by MaZderMind** [comment]
@a-tze actually we can easily integrate that info voctomix and have it create a single MKV stream with all Audio-Tracks, independent of the number of sources.
