### ISSUE TITLE
open-in-fullscreen config option

### ISSUE THREAD

**Issue by derpeter** [voc/voctomix#69]
Allow vocotomix to run in an "always full screen mode" to prevent the operator from re sizing the window by accident.

**Comment by MaZderMind** [comment]
Additionally add add an option to only disable the close button

**Comment by MaZderMind** [comment]
@fightling certainly. In a VOC-Setup we usually run voctogui in a custom window-manager (dwm), which does not show close or resizing buttons. This feature is more useful for ad-hoc setups.

**Comment by fightling** [comment]
But consider that the close button of the voctogui is an extra button within the tool bar which won't be influenced by the overlying window manager.

**Comment by MaZderMind** [comment]
is already implemented
