### ISSUE TITLE
expose voctogui lib 

### ISSUE THREAD

**Issue by CarlFK** [voc/voctomix#75]
my client uses code from voctogui/lib:
`import voctogui.lib.connection as Connection`

So it needs that to be on python's path. 
There are ways I can do that, but I think best would be if it happened as part of voctogui install:

https://github.com/CarlFK/voctomix/blob/debian/debian/rules#L26-L27
```
ln -s /usr/share/voctomix/voctogui/ \                                		
$(CURDIR)/debian/voctomix-gui/usr/lib/python3/dist-packages/voctogui
```
If the location of that lib ever moves, its installer can be updated, and my client code will keep working.

**Comment by MaZderMind** [comment]
No, that wont happen. everything under lib is private api that might change at any time in any way. Exposing it would enforce the code to be kinda stable and documented.

Of course you still can reuse code of those folders, but from a maintainer perspective this is discouraged.
