### ISSUE TITLE
Replace jpeg-Encoder for Previews

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#9]
Currently jpegenc is used to size the Video-Streams down before sending them to the voctogui, when the gui is not running on the same System.

jpegenc burns a lot of cpu and can't be used in full-hd on our hardware. Other options should be tested, to get the four video-streams through one GBit.

**Comment by MaZderMind** [comment]
piping the raw 1920×1080×YUV420×25fps Video through `lz4 -1` reduces the required Bandwith from ~600MBit/s to 280MBit/s so way more then the jpeg compression and to much to pipe the 4 video streams to the GUI over a 1GBit/s link.

**Comment by MaZderMind** [comment]
After testing various combinations, I'd opt for removing a video-encoder in this place altogether.
We should send raw I420 to the GUI.

For the Previews (3 at the side) at `320×180` this would take up `16.48 MBit/s` ×3 = `49,44 MBit/s`
For the Main-Mix at `1280×720` this would take `264 MBit/s`.
This would sum up to `313.44 MBit/s` which would fit easily onto a GBit network, leavong enough headroom, even with streams (`~10 MBit/s`) and syncing the recordings (`~100 MBit/s`) running.

**Comment by a-tze** [comment]
What about the load in sending 300 MBit/s? And is it a TCP connection? Did you also evaluate huffyuv?

**Comment by MaZderMind** [comment]
see #87 for an actual implementation
