### ISSUE TITLE
Show shortcuts in GUI

### ISSUE THREAD

**Issue by MaZderMind** [voc/voctomix#92]
Pressing the Question-Mark should show the Shortcuts on the Buttons.
If GTK can't do this, I'll rewrite the damn GUI in Qt.

**Comment by davidak** [comment]
So the button should show `Ctrl+1` instead of `B`?
That would make the button much wider and maybe break the GUI layout.

From a quick search i found [gtk.AccelLabel](http://www.pygtk.org/pygtk2reference/class-gtkaccellabel.html) but i'm not sure if it's just for menus or can achieve what you want.

**Comment by Florob** [comment]
I had wanted to play with `GtkShortcutsWindow` for a while.
I was wondering whether something like this would be sufficient for this ticket:
<http://babelmonkeys.de/~florob/voctomix-shortcuts.png>
Caveat: This requires Gtk+ >= 3.20

**Comment by MaZderMind** [comment]
This is already implemented
